apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: text-summarizer
  namespace: text-summarizer
  labels:
    app: text-summarizer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: text-summarizer
      component: api
